name: App CI (Reusable)

on:
  push:
    branches: [ main ]
    paths:
      - 'demo/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'demo/**'

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    uses: june2git/devops-templates/.github/workflows/build_and_release.yml@v1  # ← 버전 태그 고정 권장
    secrets:
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}   # gitops repo 쓰기용 PAT
    with:
      app_name: demo
      build_system: gradle
      dockerfile: demo/Dockerfile
      context: demo
      ecr_repo: demo-app
      aws_region: ap-northeast-2
      aws_role_arn: arn:aws:iam::703671922786:role/myeks-github-actions-ecr-role
      gitops_repo: june2git/gitops
      gitops_branch: main
      values_file: charts/values-prod.yaml
      push_mode: pr   # 'push' or 'pr'
